# Generated by Django 4.2.1 on 2023-05-29 19:43

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_to),
        ),
    ]
